### ISSUE TITLE
The Code Annotation Tool tool does not work 

### ISSUE THREAD

**Issue by ZhangHanDong** [CodeReadingClubs/annotation-tool#11]
![1](https://user-images.githubusercontent.com/27893/139518477-fbc547f4-577c-4e08-99d6-a5eac91a8820.PNG)
After pasting the github link, the tool warning: This is not a github link.

[https://github.com/rust-code-reading-club/rustc/issues/12 ](https://github.com/rust-code-reading-club/rustc/issues/12 )

**Comment by katjam** [comment]
Thank you for letting us know @ZhangHanDong.

@danfishgold might be part way through a refactor.

**Comment by danfishgold** [comment]
That's actually just bad error copy on my end, sorry. The problem is that the annotation tool only works with github permalinks rather than the regular urls. In order to get the permalink for a github page you need to press `Y` on the keyboard

In this case the original url (`https://github.com/rust-lang/rust/blob/master/compiler/rustc_resolve/src/check_unused.rs`) would turn into `https://github.com/rust-lang/rust/blob/22f1ad75e95500b3cab1d07c80d04c34d0f15f96/compiler/rustc_resolve/src/check_unused.rs`, which you can then paste in the annotation tool.

You can also generate the permalink using this button:

<img width="1273" alt="Screen Shot 2021-10-30 at 11 53 48" src="https://user-images.githubusercontent.com/777023/139526681-f8d9942b-c591-4de8-a413-35bd16d20cf3.png">


Thanks for flagging this issue! I'll prioritize improving the error message 😄

**Comment by ZhangHanDong** [comment]
@danfishgold  I see, Thanks
